.TH "IRagePixel" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRagePixel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRagePixelSprite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetSprite\fP (string name)"
.br
.ti -1c
.RI "void \fBSetSprite\fP (string name, int frameIndex)"
.br
.ti -1c
.RI "void \fBPlayAnimation\fP ()"
.br
.ti -1c
.RI "void \fBPlayAnimation\fP (bool forceRestart)"
.br
.ti -1c
.RI "void \fBPlayAnimation\fP (bool forceRestart, int rangeMinIndex, int rangeMaxIndex, int priority=0)"
.br
.ti -1c
.RI "void \fBPlayAnimation\fP (bool forceRestart, int[] frames, int pri=0)"
.br
.ti -1c
.RI "void \fBPlayAnimation\fP (bool forceRestart, RagePixelSprite\&.AnimationMode animMode, int rangeMinIndex, int rangeMaxIndex, int priority=0)"
.br
.ti -1c
.RI "void \fBPlayAnimation\fP (bool forceRestart, RagePixelSprite\&.AnimationMode animMode, int[] frames, int priority=0)"
.br
.ti -1c
.RI "void \fBPlayNamedAnimation\fP (string name, int priority=0)"
.br
.ti -1c
.RI "void \fBPlayNamedAnimation\fP (string name, bool forceRestart, int priority=0)"
.br
.ti -1c
.RI "void \fBPlayNamedAnimation\fP (string name, bool forceRestart, float delayFirstFrame, int priority=0)"
.br
.ti -1c
.RI "bool \fBHasNamedAnimation\fP (string name)"
.br
.ti -1c
.RI "bool \fBisPlaying\fP ()"
.br
.ti -1c
.RI "void \fBStopAnimation\fP ()"
.br
.ti -1c
.RI "int \fBGetSizeX\fP ()"
.br
.ti -1c
.RI "int \fBGetSizeY\fP ()"
.br
.ti -1c
.RI "void \fBSetSize\fP (int width, int height)"
.br
.ti -1c
.RI "Rect \fBGetRect\fP ()"
.br
.ti -1c
.RI "void \fBSetHorizontalFlip\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetVerticalFlip\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetTintColor\fP (Color color)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file IRagePixel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
