.TH "RagePixelColorPickerGUI" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelColorPickerGUI \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGUIArea\fP "
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "bool \fBHandleGUIEvent\fP (Event ev)"
.br
.ti -1c
.RI "void \fBCleanExit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvisible\fP = false"
.br
.ti -1c
.RI "bool \fBgizmoVisible\fP = false"
.br
.ti -1c
.RI "bool \fBisDirty\fP = false"
.br
.ti -1c
.RI "int \fBgizmoPositionX\fP = 0"
.br
.ti -1c
.RI "int \fBgizmoPositionY\fP = 0"
.br
.ti -1c
.RI "int \fBgizmoPixelWidth\fP = 32"
.br
.ti -1c
.RI "int \fBgizmoPixelHeight\fP = 32"
.br
.ti -1c
.RI "int \fBpositionX\fP = 0"
.br
.ti -1c
.RI "int \fBpositionY\fP = 0"
.br
.ti -1c
.RI "int \fBpixelWidth\fP = 128"
.br
.ti -1c
.RI "int \fBpixelHeight\fP = 128"
.br
.ti -1c
.RI "int \fBsplitSize\fP = 16"
.br
.ti -1c
.RI "int \fBmarginSize\fP = 5"
.br
.ti -1c
.RI "GUIArea \fBactiveArea\fP = GUIArea\&.None"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Rect \fBgizmoBounds\fP\fC [get]\fP"
.br
.ti -1c
.RI "Rect \fBbounds\fP\fC [get]\fP"
.br
.ti -1c
.RI "Color \fBselectedColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Texture2D \fBcolorPickerTexture\fP\fC [get]\fP"
.br
.ti -1c
.RI "Texture2D \fBcolorGizmoTexture\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file RagePixelColorPickerGUI\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
