.TH "RagePixelBitmap" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelBitmap \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRagePixelBitmap\fP (Color[] _pixels, int width, int height)"
.br
.ti -1c
.RI "\fBRagePixelBitmap\fP \fBGetSubImage\fP (int X, int Y, int width, int height)"
.br
.ti -1c
.RI "void \fBPasteBitmap\fP (int X, int Y, \fBRagePixelBitmap\fP bitmap)"
.br
.ti -1c
.RI "void \fBPasteBitmapAlpha\fP (int X, int Y, \fBRagePixelBitmap\fP bitmap)"
.br
.ti -1c
.RI "void \fBPasteToTextureWithBounds\fP (int X, int Y, int minX, int minY, int maxX, int maxY, Texture2D tex, Color multiplyWith)"
.br
.ti -1c
.RI "int \fBWidth\fP ()"
.br
.ti -1c
.RI "int \fBHeight\fP ()"
.br
.ti -1c
.RI "Color \fBGetPixel\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBSetPixel\fP (int x, int y, Color color)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color[] \fBpixels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file RagePixelBitmap\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
