.TH "RagePixelCell" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelCell \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearUndoHistory\fP ()"
.br
.ti -1c
.RI "ArrayList \fBGetUndoHistory\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ArrayList \fBundoHistory\fP"
.br
.ti -1c
.RI "int \fBkey\fP"
.br
.ti -1c
.RI "Rect \fBuv\fP"
.br
.ti -1c
.RI "int \fBdelay\fP"
.br
.ti -1c
.RI "string \fBimportAssetPath\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file RagePixelCell\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
