.TH "RagePixelCamera" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelCamera \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSnapToIntegerPosition\fP ()"
.br
.ti -1c
.RI "void \fBOnPostRender\fP ()"
.br
.ti -1c
.RI "void \fBOnDrawGizmosSelected\fP ()"
.br
.ti -1c
.RI "void \fBResetCamera\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpixelSize\fP = 1"
.br
.ti -1c
.RI "int \fBresolutionPixelWidth\fP = 1024"
.br
.ti -1c
.RI "int \fBresolutionPixelHeight\fP = 768"
.br
.ti -1c
.RI "bool \fBsnapToIntegerPositions\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file RagePixelCamera\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
