.TH "RagePixelSettings" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelSettings \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBshowCameraWarnings\fP = true"
.br
.ti -1c
.RI "bool \fBinitialSpritesheetGenerated\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRagePixelBitmap\fP \fBclipboard\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color[] \fBpalette\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file RagePixelSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
