.TH "RagePixelTexelRect" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelTexelRect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRagePixelTexelRect\fP (int _x, int _y, int _x2, int _y2)"
.br
.ti -1c
.RI "int \fBWidth\fP ()"
.br
.ti -1c
.RI "int \fBHeight\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBX\fP"
.br
.ti -1c
.RI "int \fBY\fP"
.br
.ti -1c
.RI "int \fBX2\fP"
.br
.ti -1c
.RI "int \fBY2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file RagePixelTexelRect\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
