.TH "RagePixelSpriteSheetEditorWindow" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelSpriteSheetEditorWindow \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSpriteSheetImportTarget\fP "
.br
.ti -1c
.RI "enum \fBSpriteSheetUpdateTarget\fP "
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSprite\fP (SpriteSheetUpdateTarget target)"
.br
.ti -1c
.RI "void \fBUpdateCell\fP (\fBRagePixelCell\fP cell, Texture2D spritesheetTexture)"
.br
.ti -1c
.RI "void \fBImportSprite\fP (SpriteSheetImportTarget target)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRagePixelSpriteSheet\fP \fBspriteSheet\fP"
.br
.ti -1c
.RI "\fBRagePixelSpriteEditor\fP \fBinspector\fP"
.br
.ti -1c
.RI "\fBRagePixelSprite\fP \fBselectedSprite\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRagePixelAnimStripGUI\fP \fBanimStripGUI\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBRagePixelSpriteSheetGUI\fP \fBspriteSheetGUI\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBRagePixelSpriteSheetGUI\fP \fBcopySpriteSheetGUI\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file RagePixelSpriteSheetEditorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
