.TH "RagePixelAnimation" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelAnimation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRagePixelAnimation\fP \fBClone\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "RagePixelSprite\&.AnimationMode \fBmode\fP = 0"
.br
.ti -1c
.RI "RagePixelSprite\&.FrameMode \fBframeMode\fP = 0"
.br
.ti -1c
.RI "int \fBstartIndex\fP"
.br
.ti -1c
.RI "int \fBendIndex\fP"
.br
.ti -1c
.RI "int[] \fBframes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file RagePixelAnimation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
