.TH "RagePixelTexel" 3 "Tue May 8 2012" "RagePixel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RagePixelTexel \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRagePixelTexel\fP (int _x, int _y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBX\fP"
.br
.ti -1c
.RI "int \fBY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file RagePixelTexel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RagePixel from the source code\&.
